# Netlify configuration for React SPA routing
[build]
  # Build command (adjust if different)
  command = "npm run build"
  # Directory to publish (adjust if different)
  publish = "dist"

# Handle client-side routing - redirect all routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: Handle specific API routes if you have a backend
# [[redirects]]
#   from = "/api/*"
#   to = "https://your-api-endpoint.com/api/:splat"
#   status = 200

# Optional: Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
