// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hshemdmizqdvkicdtfky.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhzaGVtZG1penFkdmtpY2R0Zmt5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MDMxNDYsImV4cCI6MjA2NzM3OTE0Nn0.2vmbnr5v8MMtpPHI7ZW82P_z68-OMxWH5j-Jf-hpzPs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});